apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}service
  namespace: default
spec:
  selector:
    app: {{.Values.name}}
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---

{{- if .Values.dockercfg}}  
apiVersion: v1  
kind: Secret  
metadata:  
  name: {{.Values.name}}-dockercfg  
  annotations:  
    harness.io/skip-versioning: "true" 
data:  
  .dockercfg: {{.Values.dockercfg}}  
type: kubernetes.io/dockercfg  
---  
{{- end}}  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{ .Values.namespace}}
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      {{- if .Values.dockercfg}}  
      imagePullSecrets:  
      - name: {{.Values.name}}-dockercfg  
      {{- end}} 
      containers:
      - name: {{.Values.name}}
        image: {{ .Values.image}}
        ports:
        - containerPort: 8080
