apiVersion: v1
kind: Service
metadata:
  name: petclinicservice
  namespace: default
spec:
  selector:
    app: petclinic
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: petclinic
          image: "759984737373.dkr.ecr.ap-southeast-2.amazonaws.com/kotlin:8"
          ports:
            - containerPort: 8080
